version: '3.9'


services:
  client:
    build: ./client
    volumes:
      - ./client:/client
      - /client/node_modules
    networks:
      - app
    depends_on:
      - server
    ports:
      - "3000:3000"  
  server:
    build: ./server
    volumes:
      -  ./server:/server
      -  /server/node_modules
    environment:
      PORT: 4000
    networks:
      - app
      - app-db
    depends_on:
      - postgres
    ports:
      - "4000:4000"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: perfume
    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - app-db
    ports:
      - "5433:5432"






volumes:
  postgres-data:


networks:
  app:
  app-db: